<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ูุชุฌุฑ ุงูุชุญุฑุฑ ุงูููุณู</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <img src="logo.png" alt="ุดุนุงุฑ ุงููุชุฌุฑ" class="logo">
        <h1>ูุชุฌุฑ ุงูุชุญุฑุฑ ุงูููุณู</h1>
        <nav>
            <ul>
                <li><a href="files.html">๐ ุงููููุงุช</a></li>
                <li><a href="books.html">๐ ุงููุชุจ</a></li>
                <li><a href="images.html">๐ผ๏ธ ุงูุตูุฑ</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <h2>ูุฑุญุจูุง ุจู ูู ูุชุฌุฑ ุงูุชุญุฑุฑ ุงูููุณู</h2>
        <p>ููุง ููููู ุดุฑุงุก ูููุงุช ููุชุจ ูุตูุฑ ุชุณุงุนุฏู ุนูู ุงูุชุญุฑุฑ ุงูููุณู.</p>
    </main>
    <footer>
        <p>ุฌููุน ุงูุญููู ูุญููุธุฉ &copy; 2025 ูุชุฌุฑ ุงูุชุญุฑุฑ ุงูููุณู</p>
    </footer>
</body>
</html>
